id: P005561
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W2PD19644
  title: རྩ་ཆེན་ཤིང་པར་དཔེ་རྙིང་དཔེ་དཀོན་ཕྱོགས་བསྡུས།
  author: ''
  volumes:
    a80979334e524cc1af8854e4197b235f:
      image_group_id: I2PD19696
      title: ''
      volume_number: 1
      total_pages: 167
      base_file: v001.txt
    017e3c3a3e384f0ea1a9ffb1cb859358:
      image_group_id: I2PD19697
      title: ''
      volume_number: 2
      total_pages: 419
      base_file: v002.txt
    4c6f793295a247838a8030f6d560f357:
      image_group_id: I2PD19698
      title: ''
      volume_number: 3
      total_pages: 981
      base_file: v003.txt
    5efa29c71bc94f3ab8e8f4dd52ba0da4:
      image_group_id: I2PD19699
      title: ''
      volume_number: 4
      total_pages: 70
      base_file: v004.txt
    c2b35ee6ede04abfac67df3effbd0720:
      image_group_id: I2PD19700
      title: ''
      volume_number: 5
      total_pages: 340
      base_file: v005.txt
    11486cb1eede4b28823c2f3fd846ddad:
      image_group_id: I2PD19701
      title: ''
      volume_number: 6
      total_pages: 88
      base_file: v006.txt
    ff9241768b7545649a59f60b5b1e256f:
      image_group_id: I2PD19702
      title: ''
      volume_number: 7
      total_pages: 136
      base_file: v007.txt
    a1568efbb72b40dc8f9e65c1b750dfdb:
      image_group_id: I2PD19703
      title: ''
      volume_number: 8
      total_pages: 909
      base_file: v008.txt
    c9a23cf473994a6589a3042d1a65dd9e:
      image_group_id: I2PD19704
      title: ''
      volume_number: 9
      total_pages: 186
      base_file: v009.txt
    874eafbd64ab4a5e8efb4343303eb5ec:
      image_group_id: I2PD19705
      title: ''
      volume_number: 10
      total_pages: 336
      base_file: v010.txt
    f495706041fe455186ba994d2c9f7355:
      image_group_id: I2PD19706
      title: ''
      volume_number: 11
      total_pages: 431
      base_file: v011.txt
    df30aa0fcc0c44c091c2dc42170159a4:
      image_group_id: I2PD19707
      title: ''
      volume_number: 12
      total_pages: 108
      base_file: v012.txt
    9938bc4eb1b84eb891cec55948e065f4:
      image_group_id: I2PD19708
      title: ''
      volume_number: 13
      total_pages: 154
      base_file: v013.txt
    0cd332fa4e334adb82fe9e704e967712:
      image_group_id: I2PD19709
      title: ''
      volume_number: 14
      total_pages: 300
      base_file: v014.txt
    a0e1b9c12e3d453292426f615389be3a:
      image_group_id: I2PD19710
      title: ''
      volume_number: 15
      total_pages: 512
      base_file: v015.txt
    b7cad7e5832e4b33bcc747d7a44c7569:
      image_group_id: I2PD19711
      title: ''
      volume_number: 16
      total_pages: 229
      base_file: v016.txt
    b6c894f5463b4a4988119282a10e4629:
      image_group_id: I2PD19712
      title: ''
      volume_number: 17
      total_pages: 738
      base_file: v017.txt
    3e092b7714604c1c93130e09702bf6b5:
      image_group_id: I2PD19713
      title: ''
      volume_number: 18
      total_pages: 76
      base_file: v018.txt
    0856ea5c8ea14ef0a4cc06a8b1b311c5:
      image_group_id: I2PD19714
      title: ''
      volume_number: 19
      total_pages: 110
      base_file: v019.txt
    88bcb7f292c14ee0b8870ed176df95d8:
      image_group_id: I2PD19715
      title: ''
      volume_number: 20
      total_pages: 531
      base_file: v020.txt
    9051a5acc582479c8e581f9ba6723a17:
      image_group_id: I2PD19716
      title: ''
      volume_number: 21
      total_pages: 96
      base_file: v021.txt
    a57c56fb45da40018c2bef7e0f83b4fb:
      image_group_id: I2PD19717
      title: ''
      volume_number: 22
      total_pages: 611
      base_file: v022.txt
    5647586d9711402fb728972ef26513f0:
      image_group_id: I2PD19718
      title: ''
      volume_number: 23
      total_pages: 34
      base_file: v023.txt
    4eacf43fa3454fd4a86bafb9095ebf95:
      image_group_id: I2PD19719
      title: ''
      volume_number: 24
      total_pages: 298
      base_file: v024.txt
    4a0985686b6d401c9c6070de7252deae:
      image_group_id: I2PD19720
      title: ''
      volume_number: 25
      total_pages: 187
      base_file: v025.txt
    f827cbba14f04894b5cffa2f28c2a7b5:
      image_group_id: I2PD19721
      title: ''
      volume_number: 26
      total_pages: 524
      base_file: v026.txt
    bae2900a44df4aa7ac92f321e3759eaa:
      image_group_id: I2PD19722
      title: ''
      volume_number: 27
      total_pages: 53
      base_file: v027.txt
    bc75e10efd0b4722863384bb1cbdadae:
      image_group_id: I2PD19723
      title: ''
      volume_number: 28
      total_pages: 852
      base_file: v028.txt
    59169583280a4c5d86180d828af26ef6:
      image_group_id: I2PD19724
      title: ''
      volume_number: 29
      total_pages: 682
      base_file: v029.txt
    02ac2f7be02748fbb0eeafdfeaacc387:
      image_group_id: I2PD19725
      title: ''
      volume_number: 30
      total_pages: 26
      base_file: v030.txt
    a6aa08d7bb754471a167de1e674cc86c:
      image_group_id: I2PD19726
      title: ''
      volume_number: 31
      total_pages: 165
      base_file: v031.txt
    7f6df38b17444ef99b8da169c9ead0e6:
      image_group_id: I2PD19727
      title: ''
      volume_number: 32
      total_pages: 1454
      base_file: v032.txt
    05fa1ec3592c431e96bad6cc4112e466:
      image_group_id: I2PD19728
      title: ''
      volume_number: 33
      total_pages: 252
      base_file: v033.txt
    6da9a058577e4812adb2bf02de5fe962:
      image_group_id: I2PD19729
      title: ''
      volume_number: 34
      total_pages: 114
      base_file: v034.txt
